update author modal, authorui, buttons
Actual-Chat/actual-chat pull request #1157
Opened 2023-04-18 06:04 UTC by iqmulator

2023-04-18 11:33 UTC, crui3er requested changes

2023-04-18 11:33 UTC, crui3er commented on src/dotnet/Chat.UI.Blazor/Services/AuthorUI.cs
> +    public async Task<bool> CanPeerChat(AuthorId authorId, CancellationToken cancellationToken = default)
Better to rename here and below to 'CanStartPeerChat'

2023-04-18 11:33 UTC, crui3er commented on src/dotnet/Chat.UI.Blazor/Components/AuthorModalContent.razor
> +    var name = "Name";
better to rename to 'nameTitle like 'headerTitle'

2023-04-19 06:03 UTC, alexyakunin commented
LGTM.

2023-04-19 06:04 UTC, crui3er approved these changes

2023-04-19 06:13 UTC, merged