Attachment gallery
Actual-Chat/actual-chat pull request #1257
Opened 2023-06-09 07:45 UTC by iqmulator

2023-06-09 07:50 UTC, alexis-kochetov approved these changes

2023-06-09 08:55 UTC, frolyo commented on src/dotnet/Chat.UI.Blazor/Components/ChatView/Items/Attachment/VisualMediaAttachmentList.razor
> +            else if (ratio > 0.75 && ratio <= 1.25)
`ration > 0.75` seems to be redundant although it increases readability

2023-06-09 08:56 UTC, frolyo commented on src/dotnet/Chat.UI.Blazor/Components/ChatView/Items/Attachment/VisualMediaAttachmentList.razor
> +            if (ratio <= 0.75)
suggestion: `crop = ration switch ...`

2023-06-09 08:57 UTC, frolyo commented on src/dotnet/Chat.UI.Blazor/Components/ChatView/Items/Attachment/VisualMediaAttachmentList.razor
> +        foreach (var image in imageList) {
just a suggestion: `return imageList.Select(...).ToList()`;

2023-06-09 08:58 UTC, frolyo commented on src/dotnet/Chat.UI.Blazor/Components/ChatView/Items/Attachment/VisualMediaAttachmentList.razor
> +        if (mixedList.Count <= 0) return newGallery;
new line for `return`

2023-06-09 09:23 UTC, frolyo requested changes

2023-06-09 09:23 UTC, frolyo commented on src/dotnet/Chat.UI.Blazor/Components/ChatView/Items/Attachment/VisualMediaAttachmentList.razor
> +            if (line is not { IsFull: false,Line: not null }) continue;
`continue` must be on the next line

2023-06-09 09:23 UTC, frolyo commented on src/dotnet/Chat.UI.Blazor/Components/ChatView/Items/Attachment/VisualMediaAttachmentList.razor
> +        public ImageSize ImageSize { get; set; }
why not readonly? Do you need to set them after obj was created?

2023-06-16 09:03 UTC, crui3er requested changes

2023-06-16 09:03 UTC, crui3er commented on src/dotnet/Chat.UI.Blazor/Components/ChatView/Items/Attachment/VisualMediaAttachmentList.razor
> +        foreach (var item in orderedList) {
I would even rewrite it with something like below:
```
List<ImageItem>? rowItems = null;
var lastItem = orderedList.Last();
int rowCapacity = 1;
var rowSize = ImageSize.ExtraLarge;
foreach (var item in orderedList) {
    if (rowItems != null && rowSize != item.ImageSize) {
        // image size has changed, complete the previous row
        var row = new GalleryRow(rowSize, rowItems.Count == rowCapacity, rowItems);
        gallery.Add(row);
        rowItems = null;
    }
    if (rowItems == null)
        rowItems = new List<ImageItem>();
    rowItems.Add(item);
    rowSize = item.ImageSize;
    rowCapacity = rowSize switch {
        ImageSize.ExtraLarge => 1,
        ImageSize.Large => 2,
        ImageSize.Medium => 3,
        _ => 4
        };
    if (rowItems.Count == rowCapacity || ReferenceEquals(lastItem, item)) {
        // row capacity has reached or it's a last item, complete the row
        var row = new GalleryRow(rowSize, rowItems.Count == rowCapacity, rowItems);
        gallery.Add(row);
        rowItems = null;
    }
}
```

2023-06-16 11:27 UTC, frolyo commented on src/dotnet/Chat.UI.Blazor/Components/ChatView/Items/Attachment/VisualMediaAttachmentList.razor
> +            let ratio = (float)image.Media.Width / image.Media.Height
Try double or use 0.75f to avoid casting

2023-06-20 12:43 UTC, frolyo commented on src/dotnet/Chat.UI.Blazor/Components/ChatView/Items/Attachment/VisualMediaAttachmentLine.razor
> +    if (ImageSize == ImageSize.Small) {
as far as i understand, all this long ifelse statement is about lineHeight calculation. What if we extract local function `GetLineHeight`?

2023-06-20 12:43 UTC, frolyo approved these changes

2023-06-20 15:07 UTC, crui3er approved these changes

2023-06-21 05:58 UTC, merged