feat: minimize window instead of closing
Actual-Chat/actual-chat pull request #1311
Opened 2023-07-07 19:25 UTC by crui3er

- Minimize window instead of closing
- Adds Quit item to task bar icon menu
![image](https://github.com/Actual-Chat/actual-chat/assets/20703715/4d68c235-448b-40a0-95cf-04bfd6998628)

2023-07-07 19:39 UTC, alexyakunin commented
"Quit Actual Chat"

2023-07-07 19:40 UTC, alexyakunin requested changes

2023-07-07 19:40 UTC, alexyakunin commented on src/dotnet/App.Maui/Platforms/Windows/JumpListManager.cs
> +        AddJumpListItem(jumpList, QuitArgs, "Quit", "ms-appx:///Platforms/Windows/Assets/jump_item_quit.png");
"Quit Actual Chat"

2023-07-08 17:13 UTC, crui3er commented on src/dotnet/App.Maui/Platforms/Windows/JumpListManager.cs
> +        AddJumpListItem(jumpList, QuitArgs, "Quit", "ms-appx:///Platforms/Windows/Assets/jump_item_quit.png");
changed

2023-07-10 06:31 UTC, merged