add colors, dark theme
Actual-Chat/actual-chat pull request #1613
Opened 2023-10-26 13:26 UTC by iqmulator

2023-10-26 18:00 UTC, alexis-kochetov requested changes

2023-10-26 18:00 UTC, alexis-kochetov commented on src/dotnet/Chat.UI.Blazor/Components/LeftPanel/LeftPanelButtons.razor
> +            <svg class="w-8 h-8" viewBox="0 0 37 40" fill="none" xmlns="http://www.w3.org/2000/svg">
Please don't use SVG markup at Razor - move to the file for caching purposes

2023-10-26 18:00 UTC, alexis-kochetov commented on src/dotnet/Chat.UI.Blazor/Components/Settings/SettingsModal.razor
> +    var showThemeToggle = account.IsAdmin;
please use IncompleteUI feature toggle

2023-10-27 09:41 UTC, crui3er requested changes

2023-10-27 09:41 UTC, crui3er commented on src/dotnet/Chat.UI.Blazor/Components/LeftPanel/LeftPanelButtons.razor
> +            <logo-button-svg />
I think it's useless to create web-components for just displaying SVG image. Just use img tag for that purpose.

2023-10-27 09:41 UTC, crui3er commented on src/dotnet/Chat.UI.Blazor/Components/LeftPanel/logo-button-svg.lit.ts
> +@customElement('logo-button-svg')
I think it's useless to create web-components for just displaying SVG image. Just use img tag for that purpose.

2023-10-27 09:42 UTC, crui3er commented on src/dotnet/Chat.UI.Blazor/Components/LeftPanel/LeftPanelButtons.razor
> +            <svg class="w-8 h-8" viewBox="0 0 37 40" fill="none" xmlns="http://www.w3.org/2000/svg">
Don't make lit component. Use just img tag with svg file.

2023-10-27 13:36 UTC, merged