Feat/update colors 3
Actual-Chat/actual-chat pull request #1637
Opened 2023-11-09 11:40 UTC by iqmulator

2023-11-09 14:50 UTC, alexis-kochetov commented on src/nodejs/styles/colors.css
> +    --bubble: var(--indigo-60);
--indigo-70

2023-11-10 11:37 UTC, crui3er requested changes

2023-11-10 11:37 UTC, crui3er commented on src/dotnet/Chat.UI.Blazor/Components/ChatList/ChatListSortButton.razor
> +    Class="chat-list-sort-btn btn-sm transparent"
I think better add 'transparent' to 'chat-list-sort-btn' in css

2023-11-10 11:37 UTC, crui3er commented on src/dotnet/Chat.UI.Blazor/Components/ChatMessageEditor/chat-message-editor.css
> +    @apply text-round-title;
weird name for text color 'round-title'

2023-11-10 11:37 UTC, crui3er commented on src/dotnet/Chat.UI.Blazor/Components/MarkupEditor/markup-editor.css
> +    /*@apply text-counter md:text-03 !opacity-100 truncate;*/
remove code in comments

2023-11-10 11:37 UTC, crui3er commented on src/dotnet/Chat.UI.Blazor/Components/RecordingSubHeader/RecordingSubHeader.razor
> +    @if (m.RecordingChat != null) {
Did you check how it looks like when RecordingChat != null and StopRecordingAt != null ?

2023-11-10 14:49 UTC, merged