fix: refactor all buttons (sizes, colors), fix welcome block for narrow body, refactor signin and onboarding, remove garbage
Actual-Chat/actual-chat pull request #1897
Opened 2024-04-03 15:52 UTC by iqmulator

2024-04-03 15:59 UTC, alexis-kochetov requested changes

2024-04-03 15:59 UTC, alexis-kochetov commented on src/dotnet/Chat.UI.Blazor/Components/Banners/AddChatMembersBanner.razor
> +        <IconContent><i class="text-xl icon-person-add"></i></IconContent>
Can we rename to  `Icon` and `Title` ?

2024-04-03 15:59 UTC, alexis-kochetov commented on src/dotnet/UI.Blazor/Components/Button/Button.razor
> +    [Parameter] public RenderFragment? IconContent { get; set; }
Let's rename to `Title` and `Icon`

2024-04-04 10:34 UTC, iqmulator commented on src/dotnet/Chat.UI.Blazor/Components/Banners/AddChatMembersBanner.razor
> +        <IconContent><i class="text-xl icon-person-add"></i></IconContent>
Yes, we can

2024-04-04 10:34 UTC, iqmulator commented on src/dotnet/UI.Blazor/Components/Button/Button.razor
> +    [Parameter] public RenderFragment? IconContent { get; set; }
Ok

2024-04-05 06:45 UTC, alexyakunin approved these changes

2024-04-05 07:04 UTC, alexis-kochetov approved these changes

2024-04-05 07:05 UTC, merged