feat: search in contacts #2010
Actual-Chat/actual-chat pull request #2122
Opened 2024-05-27 13:55 UTC by frolyo

2024-05-27 15:19 UTC, crui3er requested changes, later dismissed

2024-05-27 15:19 UTC, crui3er commented on src/dotnet/Chat.UI.Blazor/Services/Search/SearchUI.cs
> +    public MutableState<bool> IsSearchModeOn { get; }
better to expose it as IState<bool>

2024-05-27 15:19 UTC, crui3er commented on src/dotnet/Core/DelegatingWorker.cs
> +    bool start = true) : DelegatingWorker<Unit>(jobFactory.ToUnitTaskFactory(), stopTokenSource)
start parameter is not used, remove it

2024-05-27 16:33 UTC, frolyo commented on src/dotnet/Chat.UI.Blazor/Services/Search/SearchUI.cs
> +    public MutableState<bool> IsSearchModeOn { get; }
done

2024-05-27 16:34 UTC, frolyo commented on src/dotnet/Core/DelegatingWorker.cs
> +    bool start = true) : DelegatingWorker<Unit>(jobFactory.ToUnitTaskFactory(), stopTokenSource)
done

2024-05-28 15:09 UTC, alexis-kochetov approved these changes

2024-05-28 15:13 UTC, merged