fix: update audio panel for mobile landscape view
Actual-Chat/actual-chat pull request #2135
Opened 2024-05-30 09:47 UTC by iqmulator

2024-05-30 10:00 UTC, crui3er requested changes

2024-05-30 10:00 UTC, crui3er commented on src/dotnet/Chat.UI.Blazor/Components/ChatMessageEditor/ChatMessageEditor.razor
> +            <ChatAudioPanel Chat="@Chat" Class="right-chat-audio-panel"/>
Why ChatAudioPanel is declared twice?

2024-05-30 10:00 UTC, crui3er commented on src/dotnet/Chat.UI.Blazor/Components/ChatMessageEditor/ChatMessageEditor.razor
> +        <div class="landscape-sub-footer"></div>
What 'landscape-sub-foote' is used for?

2024-05-30 11:50 UTC, frolyo commented on src/dotnet/Chat.UI.Blazor/Components/ChatMessageEditor/chat-message-editor.css
> +    @apply landscape:bg-[var(--post-panel-narrow-landscape)];
do we really need to use arbitrary value approach here?

2024-06-03 10:29 UTC, crui3er approved these changes

2024-06-03 11:10 UTC, crui3er approved these changes

2024-06-03 11:10 UTC, crui3er commented on src/nodejs/styles/colors.css
> +    --mobile-landscape-audio-panel-button: var(--gray-30);
Where is this color used?

2024-06-03 11:10 UTC, crui3er commented on src/nodejs/styles/colors.css
> +    --mobile-landscape-audio-panel-playback-on: var(--blue-10);
Where is this colot used?

2024-06-03 12:41 UTC, iqmulator commented on src/nodejs/styles/colors.css
> +    --mobile-landscape-audio-panel-button: var(--gray-30);
![image](https://github.com/Actual-Chat/actual-chat/assets/72043982/bc0d1452-780a-4de3-a1ad-1df6b67a3138)
![image](https://github.com/Actual-Chat/actual-chat/assets/72043982/53ce22a5-cfd6-4c9c-a043-b7b112095a7b)

2024-06-03 12:42 UTC, iqmulator commented on src/nodejs/styles/colors.css
> +    --mobile-landscape-audio-panel-playback-on: var(--blue-10);
![image](https://github.com/Actual-Chat/actual-chat/assets/72043982/adaa0574-f7dc-44a5-99ba-89ac4a9bf433)
![image](https://github.com/Actual-Chat/actual-chat/assets/72043982/b0e9986e-240f-4169-bf08-29b5b84bec04)

2024-06-03 12:43 UTC, merged