new post panel, remove rounded subheader for mobile
Actual-Chat/actual-chat pull request #2372
Opened 2024-08-16 05:01 UTC by iqmulator

2024-08-20 12:37 UTC, frolyo requested changes

2024-08-20 12:37 UTC, frolyo commented on src/dotnet/UI.Blazor.App/Components/Author/AuthorCircleGroup.razor
> +    [Parameter] public bool IsForTesting { get; set; }
It's a bad pattern for production code.

2024-08-20 12:37 UTC, frolyo commented on src/dotnet/UI.Blazor.App/Components/Author/AuthorCircleGroup.razor
> +    [Parameter] public bool IsForTesting { get; set; }
And I can't find where you use it.

2024-08-20 12:37 UTC, frolyo commented on src/dotnet/UI.Blazor.App/Components/ChatHeader.razor
> +                    @if (chat.Id.IsPeerChat(out _)) {
there was property Kind

2024-08-21 09:31 UTC, frolyo approved these changes

2024-08-24 06:56 UTC, merged

2024-08-24 06:56 UTC, alexyakunin requested changes

2024-08-24 06:56 UTC, alexyakunin commented on src/dotnet/UI.Blazor.App/Components/Banners/Banners.razor
> +     <TalkingMembersBanner ChatContext="@ChatContext"/>
Rename it to "ChatActivityBanner"

2024-08-24 06:56 UTC, alexyakunin commented on src/dotnet/UI.Blazor.App/Components/Banners/banners.css
>  .talking-members-banner.banner {
And this as well.

2024-08-24 06:56 UTC, alexyakunin commented on src/dotnet/UI.Blazor.App/Components/TalkingMembersPanel/talking-members-panel.css
> +.talking-members-panel .silence-icon {
And here.