Phone sign in and verification web captcha
Actual-Chat/actual-chat pull request #2603
Opened 2024-10-20 13:09 UTC by alexis-kochetov

2024-10-20 16:20 UTC, crui3er approved these changes

2024-10-20 16:20 UTC, crui3er commented on src/dotnet/UI.Blazor/Components/SignIn/Modal/ProviderSelectStep.razor
> +                    disabled="@(codeHasBeenSent)"
brackets are excessive

2024-10-20 16:20 UTC, crui3er commented on src/dotnet/UI.Blazor/Module/BlazorUICoreModule.cs
> +        fusion.AddService<TotpUI>(ServiceLifetime.Scoped);
We usually register services with implementation factory.

2024-10-20 16:20 UTC, crui3er commented on src/dotnet/UI.Blazor/Services/CaptchaUI/CaptchaUI.cs
> +    public bool IsConfigured => !string.IsNullOrWhiteSpace(SiteKey);
Put properties above methods/constructors.

2024-10-20 16:20 UTC, crui3er commented on src/dotnet/Users.Service/Captcha.cs
> +    public void Dispose()
I nothing to do in Dispose we can remove IDisposable interface

2024-10-21 08:21 UTC, alexis-kochetov commented on src/dotnet/UI.Blazor/Module/BlazorUICoreModule.cs
> +        fusion.AddService<TotpUI>(ServiceLifetime.Scoped);
I'm not sure that we do so for Fusion services

2024-10-21 11:16 UTC, crui3er commented on src/dotnet/UI.Blazor/Module/BlazorUICoreModule.cs
> +        fusion.AddService<TotpUI>(ServiceLifetime.Scoped);
You are right. It register proxy class internally. Did not put attention that AddService is called for fusion.

2024-10-21 13:50 UTC, alexyakunin requested changes
One text edit + minor stuff.

2024-10-21 13:50 UTC, alexyakunin commented on src/dotnet/UI.Blazor/Components/Phone/PhoneVerifier.razor
> +        _ => "Verify your phone number to be able to sign in with it.",
Verify your phone number to sign in to Actual Chat.

2024-10-21 13:50 UTC, alexyakunin commented on src/dotnet/UI.Blazor/Module/BlazorUICoreModule.cs
> +        fusion.AddService<TotpUI>(ServiceLifetime.Scoped);
Yep, Fusion services activate some proxy rather than a service.

2024-10-22 05:56 UTC, merged