Chat menu
Actual-Chat/actual-chat pull request #306
Opened 2022-07-12 20:12 UTC by iqmulator

2022-07-15 11:53 UTC, iqmulator commented
![image](https://user-images.githubusercontent.com/72043982/179217699-46fccff6-23f9-4258-9108-960c1118f603.png)
![image](https://user-images.githubusercontent.com/72043982/179217731-fc1428d1-6939-4752-a7ed-36fadbeb3f25.png)
![image](https://user-images.githubusercontent.com/72043982/179217762-9ff5e8fc-d65b-4cfc-8956-f7948984f4f8.png)
![image](https://user-images.githubusercontent.com/72043982/179217784-30c18a31-613b-4ad6-8997-0b73227093eb.png)
![image](https://user-images.githubusercontent.com/72043982/179217806-456eb4f0-eed1-4368-99a1-45ef1f91fed1.png)
![image](https://user-images.githubusercontent.com/72043982/179217854-e46a780e-f816-4234-888b-2b384e58e90e.png)
![image](https://user-images.githubusercontent.com/72043982/179217874-4c7b8995-6b9a-4604-8bc9-e2fb33565280.png)
![image](https://user-images.githubusercontent.com/72043982/179217897-7f26d447-0bf5-4980-8bfb-2b16f8ae4ebf.png)
![image](https://user-images.githubusercontent.com/72043982/179217954-37fbd29a-f036-4d05-ad4f-e9203ee832cb.png)
![image](https://user-images.githubusercontent.com/72043982/179217976-c2208149-bb76-455b-a593-d24c55a9fcc1.png)
![Uploading image.png…]()

2022-07-15 11:54 UTC, iqmulator commented
![image](https://user-images.githubusercontent.com/72043982/179218143-66e4f028-b85c-465c-b202-4f2475f147f4.png)

2022-07-15 12:18 UTC, crui3er requested changes

2022-07-15 12:18 UTC, crui3er commented on src/dotnet/Chat.UI.Blazor/Components/ChatsTab.razor
> +    private bool IsListening(string chatId) {
It seems method 'IsListening' is not used.

2022-07-15 12:18 UTC, crui3er commented on src/dotnet/UI.Blazor/Components/ContextMenu/context-menu.ts
> +        const editor = document.querySelector('.chat-message-editor');
What is relation between chat-message-editor and context menu? Why does context menu know about chat-message-editor?

2022-07-18 07:23 UTC, alexis-kochetov requested changes

2022-07-18 07:23 UTC, alexis-kochetov commented on src/dotnet/Chat.UI.Blazor/Components/ChatMenu/ChatMenuPlayback.razor
> +    <MenuItem Title="Listen" Name="Listen Chat" Click="@(_ => ChatUI.IsPlaying.Value = !m.IsPlayingActive)" Class="@cls">
Let's agree to avoid any logic at markup - please extract to a method

2022-07-18 07:23 UTC, alexis-kochetov commented on src/dotnet/Chat.UI.Blazor/Components/ChatMenu/ChatMenuPlayback.razor
> +    <MenuItem Title="Listen" Name="Listen Chat" Click="@(_ => ChatUI.IsPlaying.Value = !m.IsPlayingActive)" Class="@cls">
I'm not sure that you change playback state there.

2022-07-18 15:10 UTC, merged