Feat/406 online status based on activity
Actual-Chat/actual-chat pull request #620
Opened 2022-10-24 20:36 UTC by alexyakunin

2022-10-25 14:05 UTC, alexis-kochetov commented on src/dotnet/UI.Blazor/Services/UserActivityUI/user-activity-ui.ts
> +import { EventHandler } from '../../../../nodejs/src/event-handling';
Please do not use relative path there! You can use `next-interaction` and `event-handling`

2022-10-25 14:07 UTC, alexis-kochetov requested changes
Please use proper imports of core TS code

2022-10-26 13:23 UTC, FrolYo commented on src/dotnet/UI.Blazor/Services/UserActivityUI/user-activity-ui.ts
> +import { EventHandler } from '../../../../nodejs/src/event-handling';
вщту

2022-10-27 10:10 UTC, alexis-kochetov approved these changes

2022-10-27 10:22 UTC, merged