chore: build warnings fix
Actual-Chat/actual-chat pull request #998
Opened 2023-02-21 11:46 UTC by FrolYo

2023-02-21 19:47 UTC, alexyakunin requested changes

2023-02-21 19:47 UTC, alexyakunin commented on src/dotnet/App.Maui/Platforms/Android/CronetMessageHandler.cs
> +                    : p1.NegotiatedProtocol.Equals("h2", StringComparison.Ordinal)
OrdinalEquals?

2023-02-21 19:47 UTC, alexyakunin commented on src/dotnet/Chat.Service/Chats.cs
> +            .OrderBy(a => a.Avatar.Name, StringComparer.Ordinal)
Aha, didn't know this even existed :)

2023-02-22 09:20 UTC, FrolYo commented on src/dotnet/App.Maui/Platforms/Android/CronetMessageHandler.cs
> +                    : p1.NegotiatedProtocol.Equals("h2", StringComparison.Ordinal)
done

2023-02-22 10:00 UTC, alexis-kochetov approved these changes

2023-02-22 10:00 UTC, merged